# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_video_local = QFrame(self.centralwidget)
        self.frame_video_local.setObjectName(u"frame_video_local")
        self.frame_video_local.setGeometry(QRect(450, 40, 320, 240))
        self.frame_video_local.setAutoFillBackground(False)
        self.frame_video_local.setFrameShape(QFrame.StyledPanel)
        self.frame_video_local.setFrameShadow(QFrame.Raised)
        self.frame_video_local.setLineWidth(1)
        self.frame_video_remoto = QFrame(self.centralwidget)
        self.frame_video_remoto.setObjectName(u"frame_video_remoto")
        self.frame_video_remoto.setGeometry(QRect(450, 312, 320, 240))
        self.frame_video_remoto.setFrameShape(QFrame.StyledPanel)
        self.frame_video_remoto.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(570, 17, 91, 19))
        font = QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(565, 289, 101, 19))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 30, 81, 71))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 95, 111, 19))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 115, 121, 19))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(145, 105, 16, 19))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 170, 121, 19))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(145, 50, 16, 19))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 225, 121, 19))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 205, 91, 19))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 150, 91, 19))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(145, 160, 16, 19))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 40, 111, 19))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 60, 121, 19))
        self.puerto_dest_recep_video = QLineEdit(self.centralwidget)
        self.puerto_dest_recep_video.setObjectName(u"puerto_dest_recep_video")
        self.puerto_dest_recep_video.setGeometry(QRect(160, 45, 113, 27))
        self.puerto_dest_recep_audio = QLineEdit(self.centralwidget)
        self.puerto_dest_recep_audio.setObjectName(u"puerto_dest_recep_audio")
        self.puerto_dest_recep_audio.setGeometry(QRect(160, 100, 113, 27))
        self.puerto_local_recep_video = QLineEdit(self.centralwidget)
        self.puerto_local_recep_video.setObjectName(u"puerto_local_recep_video")
        self.puerto_local_recep_video.setGeometry(QRect(160, 155, 113, 27))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(145, 215, 16, 19))
        self.puerto_local_recep_audio = QLineEdit(self.centralwidget)
        self.puerto_local_recep_audio.setObjectName(u"puerto_local_recep_audio")
        self.puerto_local_recep_audio.setGeometry(QRect(160, 210, 113, 27))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 260, 91, 19))
        self.ip_destino = QLineEdit(self.centralwidget)
        self.ip_destino.setObjectName(u"ip_destino")
        self.ip_destino.setGeometry(QRect(160, 255, 113, 27))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(145, 258, 16, 19))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 10, 201, 19))
        self.label_17.setFont(font)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 320, 171, 19))
        self.label_19.setFont(font)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(220, 320, 181, 19))
        self.label_20.setFont(font)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(200, 350, 20, 191))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.caja_resolucion = QComboBox(self.centralwidget)
        self.caja_resolucion.addItem("")
        self.caja_resolucion.addItem("")
        self.caja_resolucion.addItem("")
        self.caja_resolucion.setObjectName(u"caja_resolucion")
        self.caja_resolucion.setGeometry(QRect(20, 380, 91, 27))
        self.caja_fps = QComboBox(self.centralwidget)
        self.caja_fps.addItem("")
        self.caja_fps.addItem("")
        self.caja_fps.addItem("")
        self.caja_fps.setObjectName(u"caja_fps")
        self.caja_fps.setGeometry(QRect(20, 470, 91, 27))
        self.dial_bitrate_video = QDial(self.centralwidget)
        self.dial_bitrate_video.setObjectName(u"dial_bitrate_video")
        self.dial_bitrate_video.setGeometry(QRect(140, 410, 50, 64))
        self.dial_bitrate_video.setTabletTracking(False)
        self.dial_bitrate_video.setAcceptDrops(False)
        self.dial_bitrate_video.setAutoFillBackground(False)
        self.dial_bitrate_video.setMinimum(1)
        self.dial_bitrate_video.setMaximum(8)
        self.dial_bitrate_video.setValue(2)
        self.dial_bitrate_video.setTracking(True)
        self.dial_bitrate_video.setInvertedAppearance(False)
        self.dial_bitrate_video.setInvertedControls(False)
        self.dial_bitrate_video.setWrapping(False)
        self.dial_bitrate_video.setNotchTarget(3.700000000000000)
        self.dial_bitrate_video.setNotchesVisible(True)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 350, 91, 19))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 440, 72, 19))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(140, 390, 61, 19))
        self.caja_muestras = QComboBox(self.centralwidget)
        self.caja_muestras.addItem("")
        self.caja_muestras.addItem("")
        self.caja_muestras.addItem("")
        self.caja_muestras.setObjectName(u"caja_muestras")
        self.caja_muestras.setGeometry(QRect(220, 380, 86, 27))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(220, 350, 111, 19))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(220, 440, 101, 19))
        self.caja_bitrate_audio = QComboBox(self.centralwidget)
        self.caja_bitrate_audio.addItem("")
        self.caja_bitrate_audio.addItem("")
        self.caja_bitrate_audio.addItem("")
        self.caja_bitrate_audio.setObjectName(u"caja_bitrate_audio")
        self.caja_bitrate_audio.setGeometry(QRect(220, 470, 86, 27))
        self.dial_volumen = QDial(self.centralwidget)
        self.dial_volumen.setObjectName(u"dial_volumen")
        self.dial_volumen.setEnabled(True)
        self.dial_volumen.setGeometry(QRect(350, 410, 50, 64))
        font1 = QFont()
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.dial_volumen.setFont(font1)
        self.dial_volumen.setMouseTracking(False)
        self.dial_volumen.setAcceptDrops(True)
        self.dial_volumen.setMaximum(10)
        self.dial_volumen.setSingleStep(1)
        self.dial_volumen.setPageStep(1)
        self.dial_volumen.setValue(5)
        self.dial_volumen.setTracking(True)
        self.dial_volumen.setWrapping(False)
        self.dial_volumen.setNotchesVisible(True)
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(340, 390, 72, 19))
        self.check_mute = QCheckBox(self.centralwidget)
        self.check_mute.setObjectName(u"check_mute")
        self.check_mute.setGeometry(QRect(340, 480, 97, 25))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(280, 40, 20, 241))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.boton_iniciar = QPushButton(self.centralwidget)
        self.boton_iniciar.setObjectName(u"boton_iniciar")
        self.boton_iniciar.setGeometry(QRect(320, 210, 94, 27))
        self.boton_finalizar = QPushButton(self.centralwidget)
        self.boton_finalizar.setObjectName(u"boton_finalizar")
        self.boton_finalizar.setGeometry(QRect(320, 250, 94, 27))
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(155, 475, 41, 19))
        self.label_br_video = QLabel(self.centralwidget)
        self.label_br_video.setObjectName(u"label_br_video")
        self.label_br_video.setGeometry(QRect(140, 475, 10, 19))
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(310, 10, 91, 19))
        self.label_28.setFont(font)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(310, 40, 111, 19))
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(310, 110, 111, 19))
        self.slider_drop_video = QSlider(self.centralwidget)
        self.slider_drop_video.setObjectName(u"slider_drop_video")
        self.slider_drop_video.setGeometry(QRect(310, 70, 81, 16))
        self.slider_drop_video.setMaximum(20)
        self.slider_drop_video.setSingleStep(1)
        self.slider_drop_video.setOrientation(Qt.Horizontal)
        self.slider_drop_audio = QSlider(self.centralwidget)
        self.slider_drop_audio.setObjectName(u"slider_drop_audio")
        self.slider_drop_audio.setGeometry(QRect(310, 140, 81, 16))
        self.slider_drop_audio.setMaximum(20)
        self.slider_drop_audio.setSingleStep(1)
        self.slider_drop_audio.setOrientation(Qt.Horizontal)
        self.label_drop_video = QLabel(self.centralwidget)
        self.label_drop_video.setObjectName(u"label_drop_video")
        self.label_drop_video.setGeometry(QRect(400, 68, 21, 19))
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(423, 68, 16, 19))
        self.label_drop_audio = QLabel(self.centralwidget)
        self.label_drop_audio.setObjectName(u"label_drop_audio")
        self.label_drop_audio.setGeometry(QRect(400, 138, 21, 19))
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(423, 138, 16, 19))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(300, 180, 141, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 24))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Herramienta de videoconferencia", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"V\u00eddeo local", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"V\u00eddeo remoto", None))
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Puerto destino", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"recepci\u00f3n audio", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"recepci\u00f3n v\u00eddeo", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"recepci\u00f3n audio", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Puerto local", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Puerto local", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Puerto destino", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"recepci\u00f3n v\u00eddeo", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"IP Destino", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n de conexi\u00f3n", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n de v\u00eddeo", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n de audio", None))
        self.caja_resolucion.setItemText(0, QCoreApplication.translate("MainWindow", u"320x240", None))
        self.caja_resolucion.setItemText(1, QCoreApplication.translate("MainWindow", u"640x480", None))
        self.caja_resolucion.setItemText(2, QCoreApplication.translate("MainWindow", u"800x600", None))

        self.caja_fps.setItemText(0, QCoreApplication.translate("MainWindow", u"15", None))
        self.caja_fps.setItemText(1, QCoreApplication.translate("MainWindow", u"25", None))
        self.caja_fps.setItemText(2, QCoreApplication.translate("MainWindow", u"30", None))

        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Resoluci\u00f3n :", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"FPS :", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Bitrate :", None))
        self.caja_muestras.setItemText(0, QCoreApplication.translate("MainWindow", u"16000", None))
        self.caja_muestras.setItemText(1, QCoreApplication.translate("MainWindow", u"44100", None))
        self.caja_muestras.setItemText(2, QCoreApplication.translate("MainWindow", u"48000", None))

        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Muestras/seg :", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Bitrate (b/s) :", None))
        self.caja_bitrate_audio.setItemText(0, QCoreApplication.translate("MainWindow", u"64000", None))
        self.caja_bitrate_audio.setItemText(1, QCoreApplication.translate("MainWindow", u"128000", None))
        self.caja_bitrate_audio.setItemText(2, QCoreApplication.translate("MainWindow", u"192000", None))

        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Volumen :", None))
        self.check_mute.setText(QCoreApplication.translate("MainWindow", u"Mute", None))
        self.boton_iniciar.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.boton_finalizar.setText(QCoreApplication.translate("MainWindow", u"Finalizar", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Mbps", None))
        self.label_br_video.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Perfil AVPF", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Drop % v\u00eddeo :", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Drop % audio :", None))
        self.label_drop_video.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_drop_audio.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"%", None))
    # retranslateUi

